print("Vamos criar seu mini currículo")

nome = input("Nome completo: ")
email = input("E-mail profissional: ")
telefone = input("Telefone para contato: ")
formação = input("Formação atual: ")
habilidades = input("Liste 3 habilidades: ")
objetivo = input("Objetivo profissional: ")

print("\n Mini Currículo\n")
print(f"Nome: {nome}")
print(f"E-mail: {email}")
print(f"Telefone: {telefone}")
print(f"Formação: {formação}")
print(f"Habilidades: {habilidades}")
print(f"Objetivo: {objetivo}")
